# Load data

In [46]:
# --- IMPORTS AND SIMILAR ---#
import time
import datetime
from dateutil import tz
import sqlite3
import matplotlib.pyplot as plt
import pandas as pd

from IPython.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

stock = "ISIG"
startdate = "2017-03-13"
enddate = "2017-03-19"

# -------------- Connect to local SQLite db --------------------
#connect to SQLite database
connect = sqlite3.connect(r"C:\01 SR Data partition\TradingDatabaser\SRUSListedPolygonDaily.db")
c = connect.cursor()

In [56]:
df = (pd.read_sql("SELECT * FROM %s WHERE DATE(date) BETWEEN '%s' AND '%s' " % (stock, startdate, enddate), connect, parse_dates=['Date']) )
df.drop(["Weekday"],axis=1, inplace=True) #deleting the Weekday column just to be able to add it below
df

,Date,Stock,Open,High,Low,Close,OpenUnadjusted,HighUnadjusted,LowUnadjusted,CloseUnadjusted,MarketCap,Volume,Outstanding,$Volume,AvgVolume10D,Range,PrevDayClose
0,2017-03-13,ISIG,9.1700,9.3100,8.89,9.10,1.3100,1.3300,1.27,1.30,2298548.20,22575.0,252587.714286,206222.62500,53698.1,4.580153,8.82
1,2017-03-14,ISIG,10.2900,10.2900,9.45,9.59,1.4700,1.4700,1.35,1.37,2422316.18,9747.0,252587.714286,96885.18000,53240.6,8.163265,9.10
2,2017-03-15,ISIG,9.4787,9.5200,9.45,9.45,1.3541,1.3600,1.35,1.35,2386953.90,4833.0,252587.714286,45741.20355,53226.8,0.738498,9.59
3,2017-03-16,ISIG,9.4885,9.5200,9.45,9.45,1.3555,1.3600,1.35,1.35,2386953.90,1518.0,252587.714286,14374.32150,42240.2,0.737735,9.45
4,2017-03-17,ISIG,9.4976,9.4976,9.45,9.45,1.3568,1.3568,1.35,1.35,2386953.90,1216.0,252587.714286,11520.14080,27481.9,0.501179,9.45

# Add a weekday column - days by name

In [57]:
df['Weekday'] = df.Date.dt.day_name()
df

,Date,Stock,Open,High,Low,Close,OpenUnadjusted,HighUnadjusted,LowUnadjusted,CloseUnadjusted,MarketCap,Volume,Outstanding,$Volume,AvgVolume10D,Range,PrevDayClose,Weekday
0,2017-03-13,ISIG,9.1700,9.3100,8.89,9.10,1.3100,1.3300,1.27,1.30,2298548.20,22575.0,252587.714286,206222.62500,53698.1,4.580153,8.82,Monday
1,2017-03-14,ISIG,10.2900,10.2900,9.45,9.59,1.4700,1.4700,1.35,1.37,2422316.18,9747.0,252587.714286,96885.18000,53240.6,8.163265,9.10,Tuesday
2,2017-03-15,ISIG,9.4787,9.5200,9.45,9.45,1.3541,1.3600,1.35,1.35,2386953.90,4833.0,252587.714286,45741.20355,53226.8,0.738498,9.59,Wednesday
3,2017-03-16,ISIG,9.4885,9.5200,9.45,9.45,1.3555,1.3600,1.35,1.35,2386953.90,1518.0,252587.714286,14374.32150,42240.2,0.737735,9.45,Thursday
4,2017-03-17,ISIG,9.4976,9.4976,9.45,9.45,1.3568,1.3568,1.35,1.35,2386953.90,1216.0,252587.714286,11520.14080,27481.9,0.501179,9.45,Friday

# Add a weekday column - days by number (0 = monday)

In [58]:
df['Weekday_numbers'] = df.Date.dt.dayofweek
df

,Date,Stock,Open,High,Low,Close,OpenUnadjusted,HighUnadjusted,LowUnadjusted,CloseUnadjusted,MarketCap,Volume,Outstanding,$Volume,AvgVolume10D,Range,PrevDayClose,Weekday,Weekday_numbers
0,2017-03-13,ISIG,9.1700,9.3100,8.89,9.10,1.3100,1.3300,1.27,1.30,2298548.20,22575.0,252587.714286,206222.62500,53698.1,4.580153,8.82,Monday,0
1,2017-03-14,ISIG,10.2900,10.2900,9.45,9.59,1.4700,1.4700,1.35,1.37,2422316.18,9747.0,252587.714286,96885.18000,53240.6,8.163265,9.10,Tuesday,1
2,2017-03-15,ISIG,9.4787,9.5200,9.45,9.45,1.3541,1.3600,1.35,1.35,2386953.90,4833.0,252587.714286,45741.20355,53226.8,0.738498,9.59,Wednesday,2
3,2017-03-16,ISIG,9.4885,9.5200,9.45,9.45,1.3555,1.3600,1.35,1.35,2386953.90,1518.0,252587.714286,14374.32150,42240.2,0.737735,9.45,Thursday,3
4,2017-03-17,ISIG,9.4976,9.4976,9.45,9.45,1.3568,1.3568,1.35,1.35,2386953.90,1216.0,252587.714286,11520.14080,27481.9,0.501179,9.45,Friday,4